### ISSUE TITLE
Possibility to get track list of specified user 

### ISSUE THREAD

**Issue by auwtch** [alashow/datmusic-api#10]

**Comment by alashow** [comment]
https://github.com/alashow/datmusic-api/commit/0f55839d4cfde2330057a1ddf1953f9aa774682e adds basic functionality for getting users audios (or groups/publics).

But it doesn't work :)

The reason is: seems like VK has two versions of VK mobile version. One of them requires Javascript and the other one doesn't. It somehow detects that user doesn't have javascript enabled and disables audio pages on the non-javascript version. It just returns/redirects to logged in users audio page (not the one we requested). Audio pages of other users are available in the browser, even when javascript is blocked, but not for the scraper (us).

I don't have much time for finding a solution for this, but you could investigate it yourself. Send me a PR to [search-user](https://github.com/alashow/datmusic-api/tree/search-user) branch if you can solve it. (hint: I think they are saving some flag in the cookies).

**Comment by alashow** [comment]
I'm closing it for now, feel free top re-open if you have further questions.
