### ISSUE TITLE
How long link is available?

### ISSUE THREAD

**Issue by ANDREW-LVIV** [alashow/datmusic-api#32]
Do you know if I have send a search request and revised a json, so how long the links like /dl/a7a4d053/fcc77122 is it relevant? around one day?

Because I'm thinking is it is possible to make playlist?

**Comment by alashow** [comment]
Mp3 Url's derived from VK are valid only for 24 hours, and that's why search cache expires in 24 hours. So, links will expire in 24 hours. But if you download the link, and the mp3 gets saved in your servers mp3 cache, the link won't expire until the mp3 is removed from the cache.

**Comment by ANDREW-LVIV** [comment]
it is pity, that in order to have playlist, mp3s have to be stored on server.
ok. thanks.

**Comment by alashow** [comment]
Yes. It's because of VK limitations.

Although, I think it could be done. You could save queries before hashing it (or just replace the hashing algo to something reversible, like base64, or symmetric encryption/decryption), and then get new search results when download/stream requested and if there is no saved data in search cache.

**Comment by alashow** [comment]
Closing this for now.
Feel free to reply or reopen if you have anything in mind.

**Comment by alashow** [comment]
I have implemented it in [tasks/recoverable-cache-keys](https://github.com/alashow/datmusic-api/tree/tasks/recoverable-cache-keys) branch.

**Comment by alashow** [comment]
I will merge this to master when I will have free time to clean up the implementation.
