### ISSUE TITLE
NotFoundHttpException

### ISSUE THREAD

**Issue by Porco-Rosso** [alashow/datmusic-api#34]
I was having errors where datmusic-api was only serving several kb files instead of the actual mp3s and so I decided to run the update script. After re-adjusting my CORS preferences (this should persist across updates or be in the .env btw) and trying the api again, I get redirected to the following page below when I try to download any songs that the api finds. Do you have any idea what the problem may be?

<img width="996" alt="screen shot 2017-08-07 at 4 32 41 pm" src="https://user-images.githubusercontent.com/7024527/29028819-1be90dbe-7b8e-11e7-89d5-4d92b1d399fa.png">

**Comment by alashow** [comment]
In your `.env`, the `DATMUSIC_MP3_URL_DECODER` option should be set to true ([here](https://github.com/alashow/datmusic-api/blob/master/.env.example#L24)).
Because it defines whether to use or not to use the vk mp3 url decoder.
Without it, all urls are linked to "use vk app" mp3s (`several kb files`). This is an example of encoded url: https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=bcHLFdWqygi/hcS6cbSedMejjYyCkgvLisiejICIiXiRaICdoZ82fqyInr8lgqK9nGT0bJaqnYmBiaGdatLHgMGDjrqEpqvGjdixAb0/baKAnbyEjd8JyJPHjgiOnqqEnYrGzaGagX8OcaG4yXO9bd50obWucXqfnXb0at8fnrOImXKCbqzHhH8gAbDSmcmLktrUyIe8F2v0ydq1yZvKm2nPz2e1FMuHFJW+mN84itaJnciKF2uNyMb8AciYFN5RiIeLjtK#EaTrcxy

When enabled, URLs will be decoded to real url of real mp3:
VkMp3Decoder.php decodes it to https://cs9-13v4.userapi.com/p4/d0682b5d2de194.mp3?extra=F9WNO0WTMHbsLdTnP9AfTEZEMi9oUlL2iYYeNJQY51ufOUde3u0k3rnuOGeKXUnK9Fcu1TlOEtL9K0hPRYqJrfAaW9ZglXHZNdsWDgnjRvSzCrsvwUsp44yMwvX0_UJYkzMn31Am-4yU
This decoded url won't work now, it's expired and bound to my IP.

API throws 404 error, because I added "use vk app" mp3's md5 hash to blacklist, so api won't stream or download it.

I was thinking about adding CORS domain to .env too, thank you for suggestion.

Hope that clears it up.

**Comment by Porco-Rosso** [comment]
Thanks for the help. I managed to fix the problem for the most part. 
I am still occasionally getting the bad.mp3 error, could you explain why a blacklist is needed? When querying through datmusic.xyz the songs seem to be fine. 
Is there a cache I should clear?

**Comment by alashow** [comment]
Yes, I forgot to mention clearing cache.
Because URLs are decoded before storing in cache. You need to remove query cache only, or delete `storage/framework/cache` if you are using filesystem as cache driver.

**Comment by alashow** [comment]
Without mp3 blacklist, you would get that short mp3s. It's just an error catching, so users won't listen wrong mp3.

**Comment by Porco-Rosso** [comment]
Thanks for the prompt reply, clearing the cache did it.

**Comment by alashow** [comment]
CORS from .env f3d430364527d0700f2e8675098e2ef9b7723197
