### ISSUE TITLE
Flood control

### ISSUE THREAD

**Issue by LevanQerdikashvili** [alashow/datmusic-api#85]
hello, 
problem:
Flood control

{
    "status": "error",
    "error": {
        "message": "Flood control: too much captcha requests",
        "code": 9
    }
}

how to fix?
change tokens but result not change :/

**Comment by alashow** [comment]
That means your account might have been banned from vk. Try getting a token with a new account.
The error is caused by sending too many wrong captcha keys or requesting too many times while you need to answer the captcha. I solved this by implementing a captcha lock, which you can enable in configuration (see `config/app.php` and `.env`)
