### ISSUE TITLE
Can't open downloaded files 

### ISSUE THREAD

**Issue by Sparky-web** [alashow/datmusic-api#89]
This is weird. Files are downloading fine and appearing in storage/app/public. But when I try to open it through the link like this http://localhost:8000/links/2d/00/2d007db4c385348a0fe0a4e51364f72a/The%20Weeknd%20-%20Bliding%20lights.mp3 
it shows a 404 error. Logs seem to be fine. Can someone help me? 
<img width="1679" alt="Screenshot 2021-06-12 at 16 05 06" src="https://user-images.githubusercontent.com/65344272/121773830-199b2e80-cb98-11eb-8a8e-6c9b747cf733.png">
<img width="437" alt="Screenshot 2021-06-12 at 16 05 36" src="https://user-images.githubusercontent.com/65344272/121773833-1c961f00-cb98-11eb-80fa-1611daa84919.png">
<img width="1028" alt="Screenshot 2021-06-12 at 16 05 59" src="https://user-images.githubusercontent.com/65344272/121773835-1dc74c00-cb98-11eb-8027-8dc97d372636.png">

**Comment by alashow** [comment]
This is because in laravel you need symlink folders in storage/app/public/some-folder to public/some-folder. Read more about here: https://laravel.com/docs/8.x/filesystem#the-public-disk

But in the case of `links` folder, you shouldn't try to serve it via php/Laravel because it takes away php-fpm workers in production deployment.

That's why I created `links` folder by symlinking actual mp3 files from `storage/app/public/mp3/xx/xx/xxxx.mp3` to `storage/app/public/links/xx/xx/xxxx/Artist - Title.mp3` so I could serve mp3 files via actual webserver, i.e nginx.

You can still symlink links folder in dev mode for testing: `ln -s /full/path/to/project/storage/app/public/links /full/path/to/project/public/links`

Later, you can add this config to your nginx when you have it:
```nginx
location ~ /links/.+\.mp3$ {
     types {
      application/octet-stream;
}
```
Deployment guide: https://gist.github.com/alashow/c1a7be2020059e4ae8160328fbaf1a8c

**Comment by Sparky-web** [comment]
Thank you so much!
