### ISSUE TITLE
This project is working ?

### ISSUE THREAD

**Issue by vasea101** [alashow/datmusic-api#94]
This project is working now? If yes, install instruction is current?

**Comment by alashow** [comment]
Yes and no. Master branch that uses vk api doesn't work anymore (all audios require hsl decoding & decrypting segment order).

[deemix](https://github.com/alashow/datmusic-api/tree/deemix) branch contains integration with deemix-py, for which I wrote custom API (currently closed source, I would need a new git repo to host it because we can't host it on GH).
